---
- hosts: docker
  become: true
  tasks:
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: install dependency
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Make sure docker is installed
    service:
      name: docker
      state: started
      enabled: yes
  - name: Install docker-compose from official github repo
    get_url:
      url : https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Copy image to target
    ansible.builtin.copy:
      src: /Users/xdavidt/Documents/VCode/demo-task/image.tar.gz
      dest: /home/image.tar.gz
      follow: yes

  - name: Docker load image
    become: True
    shell:
      cmd: "docker load < image.tar.gz"
      chdir: /home/


  - name: Copy docker-compose to target
    ansible.builtin.copy:
      src: /Users/xdavidt/Documents/VCode/demo-task/docker-compose.yaml
      dest: /home/docker-compose.yaml
      follow: yes

  - name: Copy env variables to target
    ansible.builtin.copy:
      src: /Users/xdavidt/Documents/VCode/demo-task/env
      dest: /home/env
      follow: yes

  - name: Docker run compose
    become: True
    shell:
      cmd: "docker-compose --env-file env up -d"
      chdir: /home/

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted